import { IPackagesData } from '../interface';

const packageData: IPackagesData[] = [
  {
    name: 'visualMenu',
    isSpecial: false,
    title: 'منو دیداری',
    subtitle: 'منوی دیجیتال حرفه‌ای با پنل اختصاصی',
    price: '960000',
    off: '20',
    actualPrice: '768000',
    featureTitle: 'ویژگی‌هایی که خواهید داشت:',
    feature: [
      { label: 'منو آنلاین با آدرس اختصاصی' },
      { label: 'ایجاد منوهای مجزا برای سرویس های داخلی، بیرون‌بر و دلیوری' },
      { label: 'امکان درج عکس و توضیحات برای محصولات' },
      { label: 'دسته بندی آیتم‌های منو' },
      { label: 'زمانبندی برای نمایش یک دسته مانند صبحانه' },
      { label: 'درج ساعات کاری به تفکیک ایام هفته' },
      { label: 'نمایش لوگو، توضیحات و شبکه‌های اجتماعی' },
      { label: 'پنل اختصاصی برای تغییر و بروزرسانی منو' },
      { label: 'نمایش سایت رستوران در گوگل' },
      { label: 'دسترسی به منو از طریق qr کد اختصاصی' },
    ],
  },
  {
    name: 'baseMenu',
    isSpecial: false,
    title: 'پایه',
    subtitle: 'سیستم مدیریت و سفارش‌گیری هوشمند',
    price: '5760000',
    off: '20',
    actualPrice: '4608000',
    featureTitle: 'تمام امکانات منو دیداری به همراه:',
    feature: [
      { label: 'سیستم حسابداری و فروش هوشمند' },
      { label: 'سیستم ثبت سفارش آنلاین' },
      { label: 'ایجاد انواع گزارش‌های مالی و آماری' },
      { label: 'مدیریت پیک همراه با پنل اختصاصی' },
      { label: 'باشگاه مشتریان با قابلیت ارسال پیامک هوشمند' },
      { label: 'سیستم ایجاد کدهای تخفیف هوشمند و شرطی' },
      { label: 'ثبت خودکار اطلاعات مشتریان' },
      { label: 'سفارش گیر گارسون' },
      { label: 'امکان ایجاد بی نهایت چاپگر' },
    ],
  },
  {
    name: 'standardMenu',
    isSpecial: true,
    title: 'استاندارد',
    subtitle: 'پرداخت آنلاین و سامانه ارسال سفارش و پیک',
    price: '13680000',
    off: '20',
    actualPrice: '10944000',
    featureTitle: 'تمامی امکانات پلن پایه به همراه:',
    feature: [
      { label: 'درگاه پرداخت آنلاین اختصاصی' },
      { label: 'پشتیبانی از پرداخت اعتباری' },
      { label: 'قابلیت پرداخت انعام' },
      { label: 'امکان ایجاد تخفیف داینامیک' },
      { label: 'کیف پول الکترونیک' },
      { label: 'هزینه پیک داینامیک' },
      { label: 'امکان افزودن و ویرایش مشتریان به صورت گروهی' },
      { label: 'مشاهده آیتم‌های محبوب هر مشتری' },
      { label: 'شمارنده سفارش' },
    ],
  },
  {
    name: 'proMenu',
    isSpecial: false,
    title: 'حرفه ای',
    subtitle: 'مدیریت شعب، ابزار بازاریابی و باشگاه مشتریان حرفه‌ای',
    price: '21600000',
    off: '20',
    actualPrice: '17280000',
    featureTitle: 'تمامی امکانات پلن استاندارد به همراه:',
    feature: [
      { label: 'قابلیت چند شعبگی' },
      { label: 'اختصاص ضریب شارژ به مشتریان' },
      { label: 'سیستم کش بک' },
      { label: 'انبارداری هوشمند' },
      { label: 'امکان ارسال پیامک‌های شرطی و خودکار' },
      { label: 'قابلیت ایجاد کارت هدیه' },
      { label: 'سیستم رزرواسیون' },
      { label: 'پرداخت دونگی' },
      { label: 'سیستم نظرسنجی مشتریان' },
    ],
  },
];

const packageComparison = {
  digitalMenu: [
    {
      feature: 'قابلیت تعریف سایزهای مختلف برای هر آیتم',
      visualMenu: true,
      baseMenu: true,
      standardMenu: true,
      proMenu: true,
    },
    {
      feature: 'نمایش باز یا بسته بودن فروشگاه در هر لحظه',
      visualMenu: true,
      baseMenu: true,
      standardMenu: true,
      proMenu: true,
    },
    {
      feature: 'قابلیت نمایش پیشنهادات ویژه',
      visualMenu: false,
      baseMenu: true,
      standardMenu: true,
      proMenu: true,
    },
    {
      feature: 'امکان بارگذاری چندین عکس به یک محصول',
      visualMenu: false,
      baseMenu: false,
      standardMenu: true,
      proMenu: true,
    },
  ],
  ordering: [
    {
      feature: 'قابلیت تعریف سایزهای مختلف برای هر آیتم',
      visualMenu: true,
      baseMenu: true,
      standardMenu: true,
      proMenu: true,
    },
    {
      feature: 'نمایش باز یا بسته بودن فروشگاه در هر لحظه',
      visualMenu: true,
      baseMenu: true,
      standardMenu: true,
      proMenu: true,
    },
    {
      feature: 'قابلیت نمایش پیشنهادات ویژه',
      visualMenu: false,
      baseMenu: true,
      standardMenu: true,
      proMenu: true,
    },
    {
      feature: 'امکان بارگذاری چندین عکس به یک محصول',
      visualMenu: false,
      baseMenu: false,
      standardMenu: true,
      proMenu: true,
    },
  ],
};

export { packageData, packageComparison };
